version: '3.9'

services:
  record-manager-ui:
    image: 'ghcr.io/kbss-cvut/kbss-cvut/record-manager-ui:latest'
    ports:
      - '127.0.0.1:3000:80'
    depends_on:
      - record-manager
    environment:
      APP_TITLE: "Record Manager"
      BASENAME: "./"
      LANGUAGE: "en"
      NAVIGATOR_LANGUAGE: "true"
      API_URL: "http://localhost:8080/record-manager"
      APP_INFO: "<a href=\"https://github.com/kbss-cvut\" target=\"_blank\" rel=\"noopener noreferrer\" title=\"KBSS CVUT v Praze\">© KBSS CVUT v Praze, 2023</a>"

  record-manager:
    build: .
    image: record-manager
    container_name: record-manager
    ports:
      - '127.0.0.1:8080:8080'
    depends_on:
      - s-pipes-engine
      - db-server
    environment:
      REPOSITORYURL: "http://db-server:7200/repositories/record-manager"
      FORMGENREPOSITORYURL: "http://db-server:7200/repositories/record-manager-formgen"
      FORMGENSERVICEURL: "http://s-pipes-engine:8080/s-pipes/service?_pId=clone&sgovRepositoryUrl=https%3A%2F%2Fgraphdb.onto.fel.cvut.cz%2Frepositories%2Fkodi-slovnik-gov-cz"

  s-pipes-engine:
    image: 'ghcr.io/kbss-cvut/s-pipes/s-pipes-engine:latest'
    ports:
      - "127.0.0.1:8081:8080"
    depends_on:
      - db-server
    environment:
      - CONTEXTS_SCRIPTPATHS=/scripts

  db-server:
    build:
      context: db-server
    environment:
      GDB_JAVA_OPTS: -Ddefault.min.distinct.threshold=67108864
    ports:
      - "127.0.0.1:7200:7200"
    volumes:
      - data:/opt/graphdb/home

volumes:
  data:
  logs: